#!/bin/zsh

if [ "$1" = "" ]; then
    cd $HPD_PATH3
elif [ "$1" = "-a" ]; then
    HPD_PATH3=$(pwd)
    sed -i 's,\(.*HPD_PATH3=\).*$,\1\"'"$(pwd)"'\",' $HPD_PATH/hpd_data
    echo path harpooned
fi
