#!/bin/zsh

if [ "$1" = "" ]; then
    cd $HPD_PATH2
elif [ "$1" = "-a" ]; then
    HPD_PATH2=$(pwd)
    sed -i 's,\(.*HPD_PATH2=\).*$,\1\"'"$(pwd)"'\",' $HPD_PATH/hpd_data
    echo path harpooned
fi
